### PR TITLE
Comments section

### PR DESCRIPTION
**Pull request by xzebra**
As a temporary addition, I implemented the comments section. I haven't come up with a great solution to posting comments in an elegant way, as a Markdown editor would be required.

I included another Markdown element to display the comments. This made me reuse the `HyperLink ` and `CodeBlock` overrides for the Markdown component so I made an include for those. In addition, the `Comment `component reuses the `AuthorDetails`, `AuthorAvatar`... components, you could create new ones if desired.

To end, I changed a few styles to make the comments look OK and set `position: static` in `PostReaction` as now you can't use bottom as reference (I'm sure this could've been done better).

image

### CODE REVIEW

**Comment by saadpasta** [comment]
@xzebra Look's awesome. I'll have a look

**Comment by xzebra** [comment]
Sure! I will work on it

**Comment by saadpasta** [comment]
@allcontributors please add @xzebra for code and idea

**Comment by saadpasta** [comment]
@allcontributors please add @xzebra for code

**Pull request merged**
