### PR TITLE
Service Worker Register/Unregister W.R.T Environment

### PR DESCRIPTION
**Pull request by viveksharmaui**
Hi ! 
Service worker will not automatically register it we need to do it manually i added this code so that when we deploy this app in production we don't need to manually register service worker.

#slimcoder

### CODE REVIEW

**Comment by jvm-odoo** [comment]
I don't know if I can but let's try:
@allcontributors please add @viveksharmaui for code

**Comment by jvm-odoo** [comment]
Thanks for contributing @viveksharmaui!

**Comment by viveksharmaui** [comment]
My pleasure , 
Get ready for more PR's by me .

#slimcoder

**Comment by viveksharmaui** [comment]
@jvm-odoo what is bitsky ? actually i'm interested to join this organization i want to contribute something great.

**Comment by jvm-odoo** [comment]
@viveksharmaui It's a kind of social network/files cloud that you put on a Raspberry PI. If your friends have one too you can link to each others and create a single sharing space. We have a prototype which is private but the repo on my profile is the "real" version which is not ready for contributing at the moment. Thanks for asking

**Pull request merged**
